
import "./globals.css";
import NavBar from "@/components/NavBar";

import {ReactLenis} from "@/utils/lenis"


export const metadata = {
  title: "APOLLINE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     <ReactLenis root>
     <body
      className="bg-[#1E1E1C] min-h-screen text-[#D5D4D3]"
      >
        <NavBar/>
        {children}
      </body>
     </ReactLenis>
    </html>
  );
}
