import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/components/NavBar";




export const metadata = {
  title: "APOLLINE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      className="bg-[#1E1E1C] min-h-screen text-[#D5D4D3]"
      >
        <NavBar/>
        {children}
      </body>
    </html>
  );
}
